### ISSUE TITLE
Expected positive integer for height but received float

### ISSUE THREAD

**Issue by pietervanstee** [juunini/gltf-optimizer#5]
Hi,

I'm trying to compress my glb file using this gltf-optimizer.
The models without textures seem to work fine.

But I'm encountering some models where the cli tool is throwing an error:

`C:\Users\claar\AppData\Local\pnpm\global\5\.pnpm\sharp@0.31.3\node_modules\sharp\lib\is.js:124
  return new Error(
         ^

Error: Expected positive integer for height but received 176.2077922077922 of type number
    at Object.invalidParameterError (C:\Users\claar\AppData\Local\pnpm\global\5\.pnpm\sharp@0.31.3\node_modules\sharp\lib\is.js:124:10)
    at Sharp.resize (C:\Users\claar\AppData\Local\pnpm\global\5\.pnpm\sharp@0.31.3\node_modules\sharp\lib\resize.js:253:16)
    at C:\Users\claar\AppData\Local\pnpm\global\5\.pnpm\gltf-optimizer@0.4.0\node_modules\gltf-optimizer\dist\src\node\convertTextureWebP.js:53:30
    at Array.map (<anonymous>)
    at C:\Users\claar\AppData\Local\pnpm\global\5\.pnpm\gltf-optimizer@0.4.0\node_modules\gltf-optimizer\dist\src\node\convertTextureWebP.js:45:87
    at step (C:\Users\claar\AppData\Local\pnpm\global\5\.pnpm\gltf-optimizer@0.4.0\node_modules\gltf-optimizer\dist\src\node\convertTextureWebP.js:33:23)
    at Object.next (C:\Users\claar\AppData\Local\pnpm\global\5\.pnpm\gltf-optimizer@0.4.0\node_modules\gltf-optimizer\dist\src\node\convertTextureWebP.js:14:53)
    at C:\Users\claar\AppData\Local\pnpm\global\5\.pnpm\gltf-optimizer@0.4.0\node_modules\gltf-optimizer\dist\src\node\convertTextureWebP.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\claar\AppData\Local\pnpm\global\5\.pnpm\gltf-optimizer@0.4.0\node_modules\gltf-optimizer\dist\src\node\convertTextureWebP.js:4:12)

Node.js v18.8.0`

I ran this command:
`gltf-optimizer optimize -i .\model_ar_detail.glb -o .\optimized\compressed.glb --texture-compress webp --verbose`

When I list the textures used in my glb file (from their original source location), they all seem to have an integer as width and height. However the optimizer seems to read a float here.

Any solutions I can try for this?
Thank you

**Comment by angelcabrera-nr** [comment]
Hi, I can confirm this issue. It's triggered when resizing a texture with an aspect ratio that doesn't result in a whole number.

For example, resizing a 1920x951 texture to a 1024px width calculates a height of 507.2, which sharp rejects.

The solution would be to apply Math.round() to the calculated dimensions before calling sharp.resize().
